### ISSUE TITLE
Error loading script c_main

### ISSUE THREAD

**Issue by Lynx-D** [Naytoxp/atm_ui#1]
Hey, here is a bug at the line 4 of the c_main file.

![image](https://user-images.githubusercontent.com/54336136/81507856-66129b80-9300-11ea-8059-41223831c9a7.png)

**Comment by Naytoxp** [comment]
Hey, actually, this is just at the first launch of the client script, this is because the transactions logs are save client side in a Resource KVP, i will fix this tomorrow, thanks for the report

**Comment by Naytoxp** [comment]
I just fix this issue
